name: .NET Core
env: 
  SEMVER: ${{ format('0.1.0-alpha+{0}', github.run_id ) }}

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore -p:Version=${{ env.SEMVER }}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack PowerBiDiffer --configuration Release -o finalpackage --no-build -p:PackageVersion=${{ env.SEMVER }}
    - name: Publish
      run: dotnet publish
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: PowerBiDiffer
        path: finalpackage
    
